[package]
name = "rust-task"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls"] }
structopt = "0.3"
tokio = { version = "1.36", features = ["rt", "macros"]}
